-- Community: daily challenges, completions, leaderboard helpers
-- Run in Supabase SQL editor after schema.sql (or merge into your migration flow).

-- ---------------------------------------------------------------------------
-- Types & tables
-- ---------------------------------------------------------------------------
CREATE TYPE public.challenge_difficulty AS ENUM ('easy', 'medium', 'hard');

CREATE TABLE public.community_challenge_templates (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  difficulty challenge_difficulty NOT NULL,
  points integer NOT NULL CHECK (points > 0),
  title text NOT NULL,
  description text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.community_daily_challenges (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  challenge_date date NOT NULL,
  difficulty challenge_difficulty NOT NULL,
  points integer NOT NULL CHECK (points > 0),
  title text NOT NULL,
  description text,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (challenge_date, difficulty)
);

CREATE TABLE public.user_challenge_completions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
  challenge_id uuid NOT NULL REFERENCES public.community_daily_challenges (id) ON DELETE CASCADE,
  points_earned integer NOT NULL CHECK (points_earned > 0),
  completed_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, challenge_id)
);

CREATE TABLE public.community_comments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
  challenge_id uuid NOT NULL REFERENCES public.community_daily_challenges (id) ON DELETE CASCADE,
  content text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.community_reactions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
  challenge_id uuid NOT NULL REFERENCES public.community_daily_challenges (id) ON DELETE CASCADE,
  reaction_type text NOT NULL DEFAULT 'like',
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, challenge_id, reaction_type)
);

CREATE INDEX idx_completions_user ON public.user_challenge_completions (user_id);
CREATE INDEX idx_completions_completed_at ON public.user_challenge_completions (completed_at);
CREATE INDEX idx_daily_challenges_date ON public.community_daily_challenges (challenge_date);
CREATE INDEX idx_community_comments_challenge ON public.community_comments (challenge_id);
CREATE INDEX idx_community_reactions_challenge ON public.community_reactions (challenge_id);

ALTER TABLE public.community_challenge_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.community_daily_challenges ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_challenge_completions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.community_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.community_reactions ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------------------------
-- Ensure 3 global challenges per calendar day (UTC) from templates
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.ensure_community_daily_challenges (p_date date)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  diff challenge_difficulty;
  cnt integer;
  picked_id bigint;
BEGIN
  FOR diff IN SELECT unnest(
    ARRAY['easy', 'medium', 'hard']::challenge_difficulty[]
  )
  LOOP
    IF EXISTS (
      SELECT 1
      FROM public.community_daily_challenges d
      WHERE d.challenge_date = p_date
        AND d.difficulty = diff
    ) THEN
      CONTINUE;
    END IF;

    SELECT count(*)::integer INTO cnt
    FROM public.community_challenge_templates t
    WHERE t.difficulty = diff;

    IF cnt = 0 THEN
      RAISE EXCEPTION 'No community_challenge_templates for difficulty %', diff;
    END IF;

    SELECT t.id INTO picked_id
    FROM public.community_challenge_templates t
    WHERE t.difficulty = diff
    ORDER BY t.id
    OFFSET (abs(hashtext(p_date::text || diff::text)) % cnt)
    LIMIT 1;

    INSERT INTO public.community_daily_challenges (
      challenge_date,
      difficulty,
      points,
      title,
      description
    )
    SELECT
      p_date,
      t.difficulty,
      t.points,
      t.title,
      t.description
    FROM public.community_challenge_templates t
    WHERE t.id = picked_id;
  END LOOP;
END;
$$;

-- ---------------------------------------------------------------------------
-- Insert completion: enforce auth, same-day challenge, points from row
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.enforce_challenge_completion ()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  pts integer;
BEGIN
  NEW.user_id := auth.uid();
  IF NEW.user_id IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  SELECT c.points INTO pts
  FROM public.community_daily_challenges c
  WHERE c.id = NEW.challenge_id
    AND c.challenge_date = (timezone('utc', now()))::date;

  IF pts IS NULL THEN
    RAISE EXCEPTION 'Invalid or expired challenge';
  END IF;

  NEW.points_earned := pts;
  NEW.completed_at := COALESCE(NEW.completed_at, now());
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_enforce_challenge_completion
  BEFORE INSERT ON public.user_challenge_completions
  FOR EACH ROW
  EXECUTE FUNCTION public.enforce_challenge_completion ();

-- ---------------------------------------------------------------------------
-- Sync user total_points
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.sync_user_total_points ()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  IF (TG_OP = 'INSERT') THEN
    UPDATE public.users
    SET total_points = total_points + NEW.points_earned
    WHERE id = NEW.user_id;
  ELSIF (TG_OP = 'DELETE') THEN
    UPDATE public.users
    SET total_points = total_points - OLD.points_earned
    WHERE id = OLD.user_id;
  END IF;
  RETURN NULL;
END;
$$;

CREATE TRIGGER trg_sync_user_total_points
  AFTER INSERT OR DELETE ON public.user_challenge_completions
  FOR EACH ROW
  EXECUTE FUNCTION public.sync_user_total_points ();

-- ---------------------------------------------------------------------------
-- Social Policies
-- ---------------------------------------------------------------------------
CREATE POLICY community_comments_select
  ON public.community_comments
  FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY community_comments_insert
  ON public.community_comments
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY community_reactions_select
  ON public.community_reactions
  FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY community_reactions_insert
  ON public.community_reactions
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- RLS policies
-- ---------------------------------------------------------------------------
CREATE POLICY community_templates_select
  ON public.community_challenge_templates
  FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY community_daily_select
  ON public.community_daily_challenges
  FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY community_completions_select_own
  ON public.user_challenge_completions
  FOR SELECT
  TO authenticated
  USING (auth.uid () = user_id);

CREATE POLICY community_completions_insert_own
  ON public.user_challenge_completions
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid () = user_id);

-- ---------------------------------------------------------------------------
-- Leaderboard (period: week | month | all | all-time)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.get_community_leaderboard (p_period text)
RETURNS TABLE (
  rank bigint,
  user_id uuid,
  display_name text,
  avatar_url text,
  total_points bigint
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  WITH bounds AS (
    SELECT CASE lower(trim(p_period))
      WHEN 'week' THEN date_trunc('week', timezone('utc', now ()))
      WHEN 'month' THEN date_trunc('month', timezone('utc', now ()))
      WHEN 'all' THEN timestamptz '1970-01-01 00:00:00+00'
      WHEN 'all-time' THEN timestamptz '1970-01-01 00:00:00+00'
      ELSE date_trunc('week', timezone('utc', now ()))
    END AS start_ts
  ),
  scoring AS (
    SELECT
      c.user_id,
      sum(c.points_earned)::bigint AS pts
    FROM public.user_challenge_completions c
    CROSS JOIN bounds b
    WHERE c.completed_at >= b.start_ts
    GROUP BY c.user_id
    HAVING sum(c.points_earned) > 0
  )
  SELECT
    row_number() OVER (
      ORDER BY
        s.pts DESC,
        s.user_id
    )::bigint AS rank,
    s.user_id,
    coalesce(
      nullif(trim(u.username), ''),
      nullif(trim(concat_ws(' ', u.first_name, u.last_name)), ''),
      'Member'
    ) AS display_name,
    u.avatar_url,
    s.pts AS total_points
  FROM scoring s
  JOIN public.users u ON u.id = s.user_id
  WHERE u.is_active = true
  ORDER BY s.pts DESC, s.user_id
  LIMIT 100;
$$;

-- ---------------------------------------------------------------------------
-- Community stats (aggregates)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.get_community_stats ()
RETURNS json
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    json_build_object(
      'total_members', (
        SELECT count(*)::integer
        FROM public.users
        WHERE is_active = true
      ),
      'challenges_completed', (
        SELECT count(*)::integer
        FROM public.user_challenge_completions
      ),
      'active_this_week', (
        SELECT count(DISTINCT c.user_id)::integer
        FROM public.user_challenge_completions c
        WHERE c.completed_at >= date_trunc('week', timezone('utc', now ()))
      ),
      'points_distributed', (
        SELECT coalesce(sum(c.points_earned), 0)::bigint
        FROM public.user_challenge_completions c
      )
    );
$$;

-- ---------------------------------------------------------------------------
-- Recent activity feed
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.get_recent_community_achievements (p_limit integer DEFAULT 9)
RETURNS TABLE (
  display_name text,
  challenge_title text,
  points_earned integer,
  completed_at timestamptz
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    coalesce(
      nullif(trim(u.username), ''),
      nullif(trim(concat_ws(' ', u.first_name, u.last_name)), ''),
      'Member'
    ) AS display_name,
    dc.title AS challenge_title,
    c.points_earned,
    c.completed_at
  FROM public.user_challenge_completions c
  JOIN public.users u ON u.id = c.user_id
  JOIN public.community_daily_challenges dc ON dc.id = c.challenge_id
  WHERE u.is_active = true
  ORDER BY c.completed_at DESC
  LIMIT greatest(1, least(p_limit, 50));
$$;

-- ---------------------------------------------------------------------------
-- Streak: consecutive UTC days with at least one completion (anchor today or yesterday)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.community_streak_for_user (p_user_id uuid)
RETURNS integer
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  cur date := (timezone('utc', now ()))::date;
  d date;
  streak_val integer := 0;
BEGIN
  IF EXISTS (
    SELECT 1
    FROM public.user_challenge_completions x
    WHERE x.user_id = p_user_id
      AND (x.completed_at AT TIME ZONE 'UTC')::date = cur
  ) THEN
    d := cur;
  ELSIF EXISTS (
    SELECT 1
    FROM public.user_challenge_completions x
    WHERE x.user_id = p_user_id
      AND (x.completed_at AT TIME ZONE 'UTC')::date = cur - 1
  ) THEN
    d := cur - 1;
  ELSE
    RETURN 0;
  END IF;

  LOOP
    EXIT WHEN NOT EXISTS (
      SELECT 1
      FROM public.user_challenge_completions x
      WHERE x.user_id = p_user_id
        AND (x.completed_at AT TIME ZONE 'UTC')::date = d
    );
    streak_val := streak_val + 1;
    d := d - 1;
  END LOOP;

  RETURN streak_val;
END;
$$;

-- ---------------------------------------------------------------------------
-- Logged-in user summary (ranks among active users; 0 points included)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.get_my_community_stats ()
RETURNS json
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  uid uuid := auth.uid ();
  pts_all bigint;
  pts_week bigint;
  pts_month bigint;
  r_all bigint;
  r_week bigint;
  r_month bigint;
  str integer;
BEGIN
  IF uid IS NULL THEN
    RETURN json_build_object('logged_in', false);
  END IF;

  SELECT coalesce(sum(c.points_earned), 0) INTO pts_all
  FROM public.user_challenge_completions c
  WHERE c.user_id = uid;

  SELECT coalesce(sum(c.points_earned), 0) INTO pts_week
  FROM public.user_challenge_completions c
  WHERE c.user_id = uid
    AND c.completed_at >= date_trunc('week', timezone('utc', now ()));

  SELECT coalesce(sum(c.points_earned), 0) INTO pts_month
  FROM public.user_challenge_completions c
  WHERE c.user_id = uid
    AND c.completed_at >= date_trunc('month', timezone('utc', now ()));

  WITH scoring_all AS (
    SELECT
      u.id AS user_id,
      coalesce(sum(c.points_earned), 0)::bigint AS pts
    FROM public.users u
    LEFT JOIN public.user_challenge_completions c ON c.user_id = u.id
    WHERE u.is_active = true
    GROUP BY u.id
  ),
  ranked_all AS (
    SELECT
      user_id,
      rank () OVER (
        ORDER BY
          pts DESC,
          user_id
      ) AS rnk
    FROM scoring_all
  )
  SELECT rnk INTO r_all
  FROM ranked_all
  WHERE user_id = uid;

  WITH week_start AS (
    SELECT date_trunc('week', timezone('utc', now ())) AS ts
  ),
  scoring_week AS (
    SELECT
      u.id AS user_id,
      coalesce(
        sum(
          CASE
            WHEN c.completed_at >= (SELECT ts FROM week_start) THEN c.points_earned
          END
        ),
        0
      )::bigint AS pts
    FROM public.users u
    LEFT JOIN public.user_challenge_completions c ON c.user_id = u.id
    WHERE u.is_active = true
    GROUP BY u.id
  ),
  ranked_week AS (
    SELECT
      user_id,
      rank () OVER (
        ORDER BY
          pts DESC,
          user_id
      ) AS rnk
    FROM scoring_week
  )
  SELECT rnk INTO r_week
  FROM ranked_week
  WHERE user_id = uid;

  WITH month_start AS (
    SELECT date_trunc('month', timezone('utc', now ())) AS ts
  ),
  scoring_month AS (
    SELECT
      u.id AS user_id,
      coalesce(
        sum(
          CASE
            WHEN c.completed_at >= (SELECT ts FROM month_start) THEN c.points_earned
          END
        ),
        0
      )::bigint AS pts
    FROM public.users u
    LEFT JOIN public.user_challenge_completions c ON c.user_id = u.id
    WHERE u.is_active = true
    GROUP BY u.id
  ),
  ranked_month AS (
    SELECT
      user_id,
      rank () OVER (
        ORDER BY
          pts DESC,
          user_id
      ) AS rnk
    FROM scoring_month
  )
  SELECT rnk INTO r_month
  FROM ranked_month
  WHERE user_id = uid;

  SELECT public.community_streak_for_user (uid) INTO str;

  RETURN json_build_object(
    'logged_in', true,
    'rank_all', r_all,
    'rank_week', r_week,
    'rank_month', r_month,
    'points_all', pts_all,
    'points_week', pts_week,
    'points_month', pts_month,
    'streak', str
  );
END;
$$;

-- ---------------------------------------------------------------------------
-- Grants (Supabase: authenticated invokes RPCs)
-- ---------------------------------------------------------------------------
GRANT SELECT ON public.community_challenge_templates TO authenticated;
GRANT SELECT ON public.community_daily_challenges TO authenticated;
GRANT SELECT, INSERT ON public.user_challenge_completions TO authenticated;
GRANT SELECT, INSERT ON public.community_comments TO authenticated;
GRANT SELECT, INSERT, DELETE ON public.community_reactions TO authenticated;

GRANT EXECUTE ON FUNCTION public.ensure_community_daily_challenges (date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_community_leaderboard (text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_community_stats () TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_recent_community_achievements (integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_my_community_stats () TO authenticated;
