-- Delete to recreate
drop function if exists public.set_updated_at cascade;
drop function if exists public.handle_new_user cascade;

drop table if exists public.users cascade;
drop table if exists public.nutrition cascade;
drop table if exists public.products cascade;
drop table if exists public.programs cascade;
drop table if exists public.orders cascade;

drop type if exists public.fitness_goal cascade;
drop type if exists public.fitness_level cascade;
drop type if exists public.nutrition_type cascade;
drop type if exists public.order_status cascade;
drop type if exists public.product_category cascade;
drop type if exists public.user_role cascade;


-- Types
CREATE TYPE public.fitness_goal AS ENUM ('lose_weight', 'build_muscle', 'improve_endurance', 'stay_fit', 'maintain', 'performance');
CREATE TYPE public.fitness_level AS ENUM ( 'beginner', 'intermediate', 'advanced' ); 
CREATE TYPE public.nutrition_type AS ENUM ('plan', 'log');
CREATE TYPE public.order_status AS ENUM ( 'pending', 'paid', 'shipped', 'delivered', 'cancelled' ); 
CREATE TYPE public.product_category AS ENUM ('equipment', 'supplement');
CREATE TYPE public.user_role AS ENUM ('user', 'admin');


-- Tables
CREATE TABLE public.users (
    id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email text NOT NULL UNIQUE,
    username text,
    first_name TEXT,
    last_name TEXT,
    avatar_url TEXT,
    role user_role DEFAULT 'user',
    fitness_goal fitness_goal,
    fitness_level fitness_level,
    starting_weight numeric(5,2),
    current_weight numeric(5,2),
    is_active      boolean       NOT NULL DEFAULT true,
    created_at     timestamptz   NOT NULL DEFAULT now(),
    updated_at     timestamptz   NOT NULL DEFAULT now()
);
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.programs (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    description TEXT,
    cover_image TEXT,
    schedule_image TEXT,
    level fitness_level,
    goal fitness_goal,
    duration_weeks integer,
    days_per_week integer,
    is_published boolean DEFAULT false,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);
ALTER TABLE public.programs ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.nutrition (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id uuid REFERENCES public.users(id) ON DELETE SET NULL,
    type nutrition_type NOT NULL,
    title TEXT,
    goal fitness_goal,
    calories_target integer,
    protein_g integer,
    carbs_g integer,
    fats_g integer,
    meals_image TEXT,
    log_date date,
    is_published boolean DEFAULT false,
    created_at timestamptz DEFAULT now()
);
ALTER TABLE public.nutrition ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.products (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    category product_category,
    description text,
    price numeric(10,2) NOT NULL,
    stock_qty integer DEFAULT 0,
    image_url TEXT,
    is_active boolean DEFAULT true,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.orders (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id uuid REFERENCES public.users(id),
    product_id bigint REFERENCES public.products(id),
    quantity integer DEFAULT 1,
    unit_price numeric(10,2),
    status order_status DEFAULT 'pending',
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;


-- Trigger function (auto-creates a users row on auth signup)
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_users_updated_at
  BEFORE UPDATE ON public.users
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- sync new users with public.users
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER
SET search_path = '' AS $$
BEGIN
  INSERT INTO public.users (id, email, username)
  VALUES (
    NEW.id,
    NEW.email,
    NEW.raw_user_meta_data->>'name');
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
