-- Delete to recreate
drop function if exists public.handle_new_user cascade;
drop function if exists public.set_starting_weight cascade;

drop table if exists public.users cascade;
drop table if exists public.programs cascade;
drop table if exists public.nutrition cascade;
drop table if exists public.products cascade;
drop table if exists public.orders cascade;

drop type if exists public.fitness_goal cascade;
drop type if exists public.fitness_level cascade;
drop type if exists public.dietary_pref cascade;
drop type if exists public.order_status cascade;
drop type if exists public.product_category cascade;
drop type if exists public.user_role cascade;


-- Types
CREATE TYPE public.fitness_goal AS ENUM ('lose_weight', 'build_muscle', 'improve_endurance', 'stay_fit');
CREATE TYPE public.fitness_level AS ENUM ('beginner', 'intermediate', 'advanced');
CREATE TYPE public.dietary_pref AS ENUM ('standard', 'vegetarian');

CREATE TYPE public.order_status AS ENUM ('pending', 'paid', 'shipped', 'delivered', 'cancelled');
CREATE TYPE public.product_category AS ENUM ('equipment', 'supplement');
CREATE TYPE public.user_role AS ENUM ('user', 'admin');

-- ==============================================================
-- KNIS: this is edited by me (comment for mental clarity)
-- ==============================================================

-- Tables

CREATE TABLE public.programs (
    id                bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title             text NOT NULL,
    description       text,
    details_html      TEXT,
    goal              fitness_goal NOT NULL,   -- used for matching
    level             fitness_level NOT NULL,  -- used for matching
    days_per_week     integer,
    duration_weeks    integer,
    is_published      boolean DEFAULT false,
    created_at        timestamptz DEFAULT now()

);
ALTER TABLE public.programs ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.nutrition (
    id                bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title             text,
    description       text,
    details_html      TEXT,
    goal              fitness_goal NOT NULL,   -- used for matching
    dietary_pref      dietary_pref ,           -- used for matching, nullable = applies to all
    calories_target   integer,
    protein_g         integer,
    carbs_g           integer,
    fats_g            integer,
    is_published      boolean DEFAULT false,
    created_at        timestamptz DEFAULT now()
);
ALTER TABLE public.nutrition ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.users (
    id              uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email           text NOT NULL UNIQUE,
    username        text,
    first_name      text,
    last_name       text,
    avatar_url      text,
    role            user_role DEFAULT 'user',
    date_of_birth   date,
    height_cm       numeric(5,1),
    starting_weight numeric(5,2),
    current_weight  numeric(5,2),
    fitness_goal    fitness_goal,
    fitness_level   fitness_level,
    dietary_pref    dietary_pref,
    days_per_week   integer,
    created_at      timestamptz NOT NULL DEFAULT now(),
    program_id bigint REFERENCES public.programs(id) ON DELETE SET NULL,
    nutrition_id bigint REFERENCES public.nutrition(id) ON DELETE SET NULL
);
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;


-- Policies
GRANT SELECT, INSERT, UPDATE, DELETE ON public.users TO authenticated;
GRANT SELECT ON PUBLIC.programs TO authenticated;
GRANT SELECT ON PUBLIC.nutrition TO authenticated;

-- SELECT
CREATE POLICY "User can view own profile"
ON public.users
FOR SELECT
to authenticated
USING (auth.uid() = id);

-- UPDATE – simplified, and email change allowed (handled via auth)
CREATE POLICY "User can update own profile"
ON public.users
FOR UPDATE
to authenticated
USING (auth.uid() = id)
WITH CHECK (auth.uid() = id);
--
-- -- DELETE – optional, if users may delete themselves
-- CREATE POLICY "User can delete own profile"
-- ON public.users
-- FOR DELETE
-- to authenticated
-- USING (auth.uid() = id);

-- Authenticated users can view published programs
CREATE POLICY "Authenticated users can view published programs"
ON public.programs
FOR SELECT
to authenticated
USING (is_published = true);

-- Authenticated users can view published nutrition plans
CREATE POLICY "Authenticated users can view published nutrition"
ON public.nutrition
FOR SELECT
to authenticated
USING (is_published = true);


-- sync new users with public.users
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER
SET search_path = '' AS $$
BEGIN
  INSERT INTO public.users (id, email, username)
  VALUES (
    NEW.id,
    NEW.email,
    NEW.raw_user_meta_data->>'name');
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Set starting weight automatically on user update
CREATE OR REPLACE FUNCTION public.set_starting_weight()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.current_weight IS NOT NULL AND OLD.starting_weight IS NULL THEN
    NEW.starting_weight = NEW.current_weight;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_set_starting_weight
  BEFORE UPDATE ON public.users
  FOR EACH ROW EXECUTE FUNCTION public.set_starting_weight();

-- ==============================================================
-- KNIS: End of what is edited by me (comment for mental clarity)
-- ==============================================================

CREATE TABLE public.products (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    category product_category,
    description text,
    price numeric(10,2) NOT NULL,
    stock_qty integer DEFAULT 0,
    created_at timestamptz DEFAULT now()
);
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.orders (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id uuid REFERENCES public.users(id),
    product_id bigint REFERENCES public.products(id),
    quantity integer DEFAULT 1,
    unit_price numeric(10,2),
    status order_status DEFAULT 'pending',
    created_at timestamptz DEFAULT now()
);
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;


